server:
  port: 8080
#
#fxsh.es:
#  enable: false
#  config:
#    hosts: 192.168.245.128
#    ports: 9200
#    schema: http

ds.source:
   type: db
   mapperlocation: classpath:sqlmap/*.xml
# db的配置
   jdbc:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.245.128:3306/master?useUnicode=true&characterEncoding=UTF-8
    userName: root
    password: root
# es的配置
   esconfig:
    hosts: 192.168.245.128
    ports: 9200
    schema: http