server:
  port: 8032


fxsh.es:
  enable: true
  config:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.16.128:3306/sl?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.245.128:3306/master?useUnicode=true&characterEncoding=UTF-8
    userName: root
    password: root